version: '3.8'

services:
  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"

  vote:
    build: ./vote
    container_name: vote
    ports:
      - "5000:5000"
    depends_on:
      - redis

  result:
    build: ./result
    container_name: result
    ports:
      - "5001:5001"
    depends_on:
      - redis
